spring.config.import=optional:file:.env[.properties]
spring.application.name=backend

spring.datasource.url=jdbc:postgresql://pg-33e1c034-smartstudy.c.aivencloud.com:27985/defaultdb?sslmode=require
spring.datasource.username=avnadmin
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true

jwt.secret=${JWT_SECRET}
jwt.expiration-ms=86400000